---
- hosts: all
  gather_facts: false

  tasks:
    - name: Copy environment template
      ansible.builtin.template:
        src: environment.j2
        dest: "{{ env_file_path }}"

    - name: Start redmine container
      become: true
      community.docker.docker_container:
        name: app
        image: "redmine:latest"
        restart_policy: always
        state: started
        env_file: "{{ env_file_path }}"
        ports:
          - 80:3000
