---
- hosts: all
  gather_facts: false

  tasks:
    - name: Install aptitude
      become: true
      apt:
        name: aptitude
        state: latest
        update_cache: true
      tags: necessary

    - name: Install required system packages
      become: true
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
      tags: necessary

    - name: Add Docker GPG apt Key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: necessary

    - name: Add Docker Repository
      become: true
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      tags: necessary

    - name: Update apt and install docker-ce
      become: true
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      tags: necessary

    - name: Install Docker Module for Python
      include_role:
        name: geerlingguy.pip
      vars:
        ansible_become: true
      tags: necessary

- hosts: webservers
  roles:
    - { role: datadog.datadog, become: true }
  tags: monitoring
