---
- hosts: webservers
  roles:
    - { role: datadog.datadog, become: yes }
  vars:
    datadog_site: "datadoghq.eu"
    datadog_agent_version: "7.41.1"
    
    datadog_config:
      logs_enabled: true
    
    datadog_checks:
      http_check:
        init_config:

        instances:
          - name: Localhost
            url: http://localhost
    
    network_config:
      enabled: true
