---
- hosts: all
  gather_facts: no
  
  tasks:
    - name: Start redmine container
      become: yes
      community.docker.docker_container:
        name: app
        image: "redmine:latest"
        restart_policy: always
        state: started
        ports:
          - 80:3000
          - 443:3000